site_name: Documentação  
site_url: https://testedocumentacao.github.io/Documentacao/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

theme:
  name: material
  logo: img/Logo_UFJF.png
  
nav:
  - Home: index.md
  - MkDocs:
    - Guia de instalação: install.md
    - Configurando MkDocs: configurations.md
    - Guia de uso MkDocs: useMkdocs.md
    - Configurando repositorio: serverConfig.md
  - Sobre: about.md
