site_name: Documentação  
site_url: https://testedocumentacao.github.io/Documentacao/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

theme:
  name: material
  logo: img/Logo_UFJF.png
  
nav:
  - Home: index.md
  
  - MkDocs:
    - Guia de instalação: mkdocs/install.md
    - Configurando MkDocs: mkdocs/configurations.md
    - Guia de uso MkDocs: mkdocs/useMkdocs.md
    - Configurando repositorio: mkdocs/serverConfig.md
    
  - Ticket UFJF:
    - Guia de uso: ticket/ticket_ufjf.md
    
  - Sobre: about.md
