site_name: Documentação 

theme:
 name: readthedocs
 
nav:
  - Home: index.md
  - Guia de instalacao: install.md
  - Configurando Mkdocs: configurations.md
  - Guia de uso Mkdocs: useMkdocs.md
  - sobre: about.md
