site_name: Documentação 
site_url: https://testedocumentacao.github.io/Documentacao/

theme:
  name: material
  
nav:
  - Home: index.md
  - MkDocs:
    - Guia de instalação: install.md
    - Configurando MkDocs: configurations.md
    - Guia de uso MkDocs: useMkdocs.md
    - Configurando repositorio: serverConfig.md
  - Sobre: about.md
